### ISSUE TITLE
'startsWith' of null

### ISSUE THREAD

**Issue by DouglasHennrich** [ewanharris/titanium-codemods#5]
I'm trying your package but when I run it, I have this error:

```shell
[8:11]➜  Ecombo  titanium-codemods ~/Documents/Projects/Up/Ecombo run --dry-run
? Select transforms (Press <space> to select, <a> to toggle all, <i> to invert selection)getter-deprecation, setter-deprecation
Using 7.5.0.GA for api.jsca file
Running getter-deprecation
Processing 38 files... 
Spawning 7 workers...
Running in dry mode, no files will be written! 
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 2 files to free worker...
Ran into problem transforming /Users/douglashennrich/Documents/Projects/Up/Ecombo/app/models/user.js
TypeError: Cannot read property 'startsWith' of null
    at startsWith (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:88:17)
    at NodePath.lookupCall (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:53:23)
    at __paths.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:76:18)
    at forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:26:5)
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Worker.js:146:23
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Ran into problem transforming /Users/douglashennrich/Documents/Projects/Up/Ecombo/app/lib/core/moment.js
TypeError: Cannot read property 'startsWith' of null
    at startsWith (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:88:17)
    at NodePath.lookupCall (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:53:23)
    at __paths.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:76:18)
    at forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/getter-deprecation.js:26:5)
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Worker.js:146:23
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
All done. 
Results: 
0 errors
0 unmodified
38 skipped
0 ok
Time elapsed: 5.581seconds 
Running setter-deprecation
Processing 38 files... 
Spawning 7 workers...
Running in dry mode, no files will be written! 
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 6 files to free worker...
Sending 2 files to free worker...
Ran into problem transforming /Users/douglashennrich/Documents/Projects/Up/Ecombo/app/models/user.js
TypeError: Cannot read property 'startsWith' of null
    at startsWith (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:93:17)
    at NodePath.lookupCall (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:54:23)
    at __paths.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:76:18)
    at forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:27:5)
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Worker.js:146:23
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
Ran into problem transforming /Users/douglashennrich/Documents/Projects/Up/Ecombo/app/lib/core/moment.js
TypeError: Cannot read property 'startsWith' of null
    at startsWith (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:93:17)
    at NodePath.lookupCall (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:54:23)
    at __paths.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:77:36)
    at Array.forEach (<anonymous>)
    at Collection.forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Collection.js:76:18)
    at forEach (/Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/transforms/setter-deprecation.js:27:5)
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/jscodeshift/src/Worker.js:146:23
    at /Users/douglashennrich/.nvm/versions/node/v10.15.0/lib/node_modules/titanium-codemods/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
All done. 
Results: 
0 errors
0 unmodified
38 skipped
0 ok
Time elapsed: 5.439seconds
```

And this is my `models/user.js`:
```js
/* ===============================
@ Dependencies
=============================== */
// const util = require('util');
import { Request } from '/core/request'
import { defer as Defer } from '/core/Q'
import { init as PushInit } from '/core/pushnotification'
import moment from '/core/moment'
import { fixProperties, safeGet } from '/util'

/* ===============================
@ Functions
=============================== */
/*
@ parentNodeFunc
*/
const parentNodeFunc = (res, xhr, collection) => {
	// Alloy.Log('[USER - parentNodeFunc]:', res);
	// Alloy.Log('[USER - parentNodeFunc] xhr:', xhr.opts);

	if (res.Data) {
		res = res.Data
	}

	// Returns if we're a model instead of collection
	if (collection instanceof Backbone.Model) return res

	// If no data returns and we're paging
	// set collection to finished
	if (!res.length && xhr.opts.add) {
		collection.finished = true
	}

	if (!res.length && !xhr.opts.add && !xhr.opts.notSaving) {
		res[0] = {
			empty: true,
			empty_title: xhr.opts.data.emptyData,
			template: 'empty',
		}
		collection.finished = true
	}

	return res
}

/* ===============================
@ Exports
=============================== */
exports.definition = {
	config: {
		URL: (endpoint, full) => (full ? endpoint : Alloy.CFG.API.BASE + endpoint),
		parentNode: parentNodeFunc,
		headers: () => ({
			Authorization: `Bearer ${Alloy.Models.user.get('accessToken')}`,
		}),
		adapter: {
			collection_name: 'user',
			idAttribute: 'modelId',
		},
		defaults: {
			coins: 1000,
		},
	},

	extendModel(Model) {
		Object.assign(Model.prototype, {
			/*
      @ SyncData
      */
			SyncData() {
				// Ti.App.Properties.removeProperty('Skapp_user')

				if (Ti.App.Properties.getObject('Skapp_user')) {
					this.set(Ti.App.Properties.getObject('Skapp_user'))

					if (!this.has('vehicle')) {
						this.set({
							vehicle: [],
						})
						this.UpdateModel()
					}

					_.defer(() => {
						// this.RegisterPush()
					})
				}

				Alloy.Log(`[User - SyncData]: ${JSON.stringify(this.toJSON())}`)
			},

			/*
      @ Transform
      */
			transform() {
				const m = this.toJSON()
				const t = this.toJSON()
				const hasUser = safeGet(m, 'user')

				if (hasUser) {
					//
					Object.defineProperty(t, 'tModel', {
						get: () => {
							const model = safeGet(m.vehicle[0], 'modelo')
							return model || null
						},
					})

					//
					Object.defineProperty(t, 'tBoard', {
						get: () => {
							const plate = safeGet(m.vehicle[0], 'placa')
							return plate || null
						},
					})
				}

				return t
			},

			/*
      @ Logged?
      */
			Logged() {
				return this.get('logged')
			},

			/*
      @ Logout
      */
			Logout(Next = () => {}) {
				this.clear()
				Ti.App.Properties.removeProperty('Skapp_user')
				this.trigger('change')
				Next()
			},

			/*
      @ UpdateModel
      */
			UpdateModel(params) {
				const opts = _.clone(params)

				if (opts) {
					this.set(opts)
				}

				Ti.App.Properties.setObject('Skapp_user', this.toJSON())
				Alloy.Log(`[User - UpdateModel]: ${JSON.stringify(this.toJSON())}`)
				this.trigger('change')
			},

			/*
      @ RegisterPush
      */
			RegisterPush(skip, token) {
				if (!skip) return PushInit()

				//
				const opts = {
					url: Alloy.CFG.API.USER.PUSHREGISTER,
					notSaving: true,
					headers: {
						Authorization: `Bearer ${this.get('accessToken')}`,
					},
					data: {
						os: OS_IOS ? 'iOS' : 'Android',
						token,
					},
				}

				Alloy.Log(`[User - RegisterPush] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - RegisterPush] res: ${JSON.stringify(res)}`)
					})
					.catch(err => {
						Alloy.Log(`[User - RegisterPush] err: ${JSON.stringify(err)}`, 'error')
					})
			},

			/*
      @ SignIn
      */
			SignIn(params) {
				const Promise = Defer()

				const { phone: fone, name: nome, password: senha, email } = params

				const opts = {
					url: Alloy.CFG.API.USER.SIGNIN,
					data: {
						fone,
						nome,
						senha,
						email,
					},
					notSaving: true,
				}

				Alloy.Log(`[User - SignIn] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - SignIn] res: ${JSON.stringify(res)}`)
						Promise.resolve(res)
					})
					.catch(err => {
						Alloy.Log(`[User - SignIn] err: ${JSON.stringify(err)}`, 'error')
						Promise.reject(err)
					})

				return Promise.promise
			},

			/*
      @ Login
      */
			Login(params) {
				const Promise = Defer()

				const { phone: fone, password: senha } = params

				const opts = {
					url: Alloy.CFG.API.USER.LOGIN,
					data: {
						fone,
						senha,
					},
					notSaving: true,
				}

				Alloy.Log(`[User - Login] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - Login] res: ${JSON.stringify(res)}`)
						if (_.isArray(res)) {
							;[res] = res
						}

						this.UpdateModel({
							logged: true,
							accessToken: res.accessToken,
							user: fixProperties(res.user),
							vehicle: res.vehicle || [],
						})

						Promise.resolve(res.user)
					})
					.catch(err => {
						Alloy.Log(`[User - Login] err: ${JSON.stringify(err)}`, 'error')
						Promise.reject(err)
					})

				return Promise.promise
			},

			/*
			@ UpdatePerfil
			*/
			UpdatePerfil(params) {
				const p = Defer()
				const { nome, email, fone, senha } = params
				const opts = {
					data: {
						nome,
						email,
						fone,
						senha,
					},
					url: Alloy.CFG.API.USER.UPDATE,
					notSaving: true,
				}

				Alloy.Log(`[User - UpdatePerfil] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - UpdatePerfil] res: ${JSON.stringify(res)}`)
						if (_.isArray(res)) {
							;[res] = res
						}

						// this.UpdateModel({
						// 	user: fixProperties(res),
						// })

						p.resolve(res)
					})
					.catch(err => {
						Alloy.Log(`[User - UpdatePerfil] err: ${JSON.stringify(err)}`, 'error')
						p.reject(err)
					})

				return p.promise
			},

			/*
			@ CreateVehicle
			*/
			CreateVehicle(params) {
				const Promise = Defer()

				const { placa, modelo } = params

				const opts = {
					url: Alloy.CFG.API.USER.VEHICLE,
					data: {
						placa,
						modelo,
					},
					notSaving: true,
				}

				Alloy.Log(`[User - CreateVehicle] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - CreateVehicle] res: ${JSON.stringify(res)}`)

						if (_.isArray(res)) {
							;[res] = res
						}

						this.UpdateModel({
							vehicle: [
								{
									placa,
									modelo,
									id_vehicle: res.id_vehicle,
								},
							],
						})

						Promise.resolve(res)
					})
					.catch(err => {
						Alloy.Log(`[User - CreateVehicle] err: ${JSON.stringify(err)}`, 'error')
						Promise.reject(err)
					})

				return Promise.promise
			},

			/*
			@ GetVehicles
			*/
			GetVehicles() {
				const p = Defer()
				const opts = {
					url: Alloy.CFG.API.USER[this.get('user').tipo === 0 ? 'VEHICLE' : 'HOIST'],
					requestMethod: 'GET',
					notSaving: true,
				}

				Alloy.Log(`[User - GetVehicles] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(res => {
						Alloy.Log(`[User - GetVehicles] res: ${JSON.stringify(res)}`)

						this.UpdateModel({
							vehicle: res || [],
						})

						p.resolve(res)
					})
					.catch(err => {
						Alloy.Log(`[User - GetVehicles] err: ${JSON.stringify(err)}`, 'error')
						p.reject(err)
					})

				return p.promise
			},

			/*
			@ SendLocation
			*/
			SendLocation(params) {
				const { latitude, longitude, currentStage, requestHoistId } = params
				const opts = {
					url: Alloy.CFG.API.SENDLOCATION,
					data: {
						latitude,
						longitude,
						currentStage,
						requestHoistId,
					},
					notSaving: true,
				}

				Alloy.Log(`[User - SendLocation] opts: ${JSON.stringify(opts)}`)

				Request(opts, this)
					.then(success => {
						Alloy.Log(`[User - SendLocation] success: ${JSON.stringify(success)}`)
					})
					.catch(err => {
						Alloy.Log(`[User - SendLocation] err: ${JSON.stringify(err)}`)
					})
			},
		})

		return Model
	},
}
```

**Comment by ewanharris** [comment]
Thanks for the report @DouglasHennrich! I just pushed v1.1.0 which should fix this
